In [1]:
import os 
os.makedirs('Ashuka',exist_ok=True)
 
print(os.getcwd()) # returns the current working directory

print(os.listdir()) # returns a list of all files and folders in the current directory

E:\Learning_Data_Science\NumPy
['.ipynb_checkpoints', 'Array1.npy', 'Ashuka', 'env', 'NumPy1.ipynb', 'NumPy2.ipynb', 'SymPy.ipynb']


### Einstein Summation Convention

In [7]:
import numpy as np

a= np.array([10,20,30,40,50,60,70,80,90]).reshape(3,3)
b= np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)

print('a:',a,'b:',b, sep = '\n')

a:
[[10 20 30]
 [40 50 60]
 [70 80 90]]
b:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
# prints the diagonal elements
print(np.einsum('ii->i',a))
print(np.einsum('ii->i',b))

[10 50 90]
[1 5 9]


In [10]:
# Sum of all elements

print(np.einsum('ij->i',b)) # row-wise
print(np.einsum('ij->j',b)) # column-wise

[ 6 15 24]
[12 15 18]


In [13]:
#Transpose of Matrix

a= np.array([10,20,30,40,50,60,70,80,90]).reshape(3,3)

print(f'Original Matrix : \n{a}')
print('Transpose of the Matrix :',np.einsum('ij->ji',a),sep = '\n')

Original Matrix : 
[[10 20 30]
 [40 50 60]
 [70 80 90]]
Transpose of the Matrix :
[[10 40 70]
 [20 50 80]
 [30 60 90]]


In [5]:
# Matrix Multilication
# repeated index (j) → multiply and sum over that dimension
# unrepated indices (i,k) → kept in the output

np.einsum('ij,jk',a,b)

array([[ 300,  360,  420],
       [ 660,  810,  960],
       [1020, 1260, 1500]])

In [14]:
np.einsum('ij,jk -> ik',a,b) #same

array([[ 300,  360,  420],
       [ 660,  810,  960],
       [1020, 1260, 1500]])

In [6]:
# Sum of diagonals

np.einsum('ii',a)

np.int64(150)

In [7]:
# matrix-vector multiplication

x = np.array([[1,2],[3,4],[5,6]])
y = np.array([7,8])

np.einsum('ij,j->i',x,y)

array([23, 53, 83])

In [15]:
s = np.arange(10,26).reshape(4,4)
s

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25]])

In [16]:
np.linalg.det(s) # gives the determinant of a matrix

np.float64(8.067895621578512e-31)

In [17]:
np.linalg.inv(s) # gives the inverse of a matrix

array([[-5.00399959e+14,  1.00079992e+14,  1.30103989e+15,
        -9.00719925e+14],
       [-1.10087991e+16,  1.21096790e+16,  8.80703927e+15,
        -9.90791918e+15],
       [ 2.35187981e+16, -2.45195980e+16, -2.15171982e+16,
         2.25179981e+16],
       [-1.20095990e+16,  1.23098390e+16,  1.14091191e+16,
        -1.17093590e+16]])

In [19]:
# solving the two equations:
# 2x + 3y = 4
# 3x + 5y = 12

A = np.array([[2,3],[3,5]])

print('No of Rows:',A.shape[0])
print('No of Columns:',A.shape[1])

b = np.array([4,12])

np.linalg.solve(A,b) 

No of Rows: 2
No of Columns: 2


array([-16.,  12.])

In [20]:
# Finding the Eigen Values and Vectors

np.linalg.eig(s)

EigResult(eigenvalues=array([ 7.11247837e+01+0.0000000e+00j, -1.12478374e+00+0.0000000e+00j,
       -2.83662080e-15+6.7700957e-16j, -2.83662080e-15-6.7700957e-16j]), eigenvectors=array([[-0.32127676+0.j        ,  0.70087495+0.j        ,
         0.10330052-0.06997964j,  0.10330052+0.06997964j],
       [-0.43035796+0.j        ,  0.25454278+0.j        ,
        -0.53507728+0.10496946j, -0.53507728-0.10496946j],
       [-0.53943916+0.j        , -0.19178939+0.j        ,
         0.76025301+0.j        ,  0.76025301-0.j        ],
       [-0.64852036+0.j        , -0.63812155+0.j        ,
        -0.32847624-0.03498982j, -0.32847624+0.03498982j]]))

In [21]:
# creating an identity matrix

np.identity(5) 

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
# creating a matrix similar to identity matrix but it can be of any shape (not only square)

np.eye(5,3) 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
sn = np.array([[8,-8,-2],[4,-3,-2],[3,-4,1]])

eigen_value, eigen_vector = np.linalg.eig(sn)

print('Eigen Values:',eigen_value,'Eigen Values:',eigen_vector,sep = '\n' )

Eigen Values:
[1. 3. 2.]
Eigen Values:
[[-0.74278135 -0.81649658 -0.80178373]
 [-0.55708601 -0.40824829 -0.53452248]
 [-0.37139068 -0.40824829 -0.26726124]]


#### Qn: Given matrices:

A = [[1,5,-3],[2,1,0],[5,3,2]]  
B = [[6,7,8],[9,-5,11],[-5,-6,10]]  
v = [7,8,9]  

Perform the following operations:  

* Compute matrix C using the formula:

$$ C = A^T + B^T + 5(A^T×A) + 6(B^T×A^T×A^{-1}×B^{-1}) + det(A)×det(B) - 6(A×B×I) $$

* Find the determinant, eigenvalues, eigenvectors and rank of C

* Compute:
$$ d = Av + Bv + Cv$$
* Check if d is:

i. a 1D array (not a matrix)  
ii. a singular matrix (det = 0)  
iii. a non-singular matrix (det ≠ 0)  
iv. a non-square matrix (determinant cannot be calculated)

In [34]:
A = np.array([[1,5,-3],[2,1,0],[5,3,2]])
B = np.array([[6,7,8],[9,-5,11],[-5,-6,10]])

at = np.einsum('ij->ji',A)
bt = np.einsum('ij->ji',B)

ai = np.linalg.inv(A)
bi = np.linalg.inv(B)

ad = np.linalg.det(A)
bd = np.linalg.det(B)
i = np.identity(3)

c = at + bt + 5*at*A + 6*bt*at*ai*bi + ad*bd - 6*A*B*i
print('Value of c:',c,sep ='\n')
dc = np.linalg.det(c)

eigen_valuec, eigen_vectorc = np.linalg.eig(c)

print('\nEigen Values of c:',eigen_valuec,sep ='\n')
print('\nEigen Vectors of c:',eigen_vectorc,sep ='\n')

rank = np.linalg.matrix_rank(c) #0 wala row herne

print('\nRank of c:',rank)

v = np.array([7,8,9])
A = np.array([[1,5,-3],[2,1,0],[5,3,2]])

va = np.einsum('ij,j->i',A,v)
vb = np.einsum('ij,j->i',B,v)
vc = np.einsum('ij,j->i',c,v)

d = va + vb + vc
r = np.shape(d)
print('\nValue of d',d,sep = '\n')


if d.ndim == 1: # ndim checks the dimension 
    print('\nIt is not a matrix.')
    
elif (d.ndim > 1) and (d.shape[0] == d.shape[1]) and np.linalg.det(d) == 0:
    print('\nIt is a singular matrix.')
    
elif (d.ndim > 1) and (d.shape[0] == d.shape[1]) and np.linalg.det(d) != 0:
    print('\nIt is a not a singular matrix.')
    
else:
    print('\nIt is not a square matrix so, determinant cannot be calculated')


Value of c:
[[32547.03536889 32639.43409782 32494.38353136]
 [32636.73952289 32600.43418992 32568.11936999]
 [32501.34926775 32582.         32486.08372479]]

Eigen Values of c:
[ 9.76853030e+04  2.24361614e+01 -7.41858388e+01]

Eigen Vectors of c:
[[-0.57732473 -0.60505496  0.53284216]
 [-0.57805938 -0.17118194 -0.8018228 ]
 [-0.57666585  0.77756366  0.27048   ]]

Rank of c: 3

Value of d
[781584.172147   782517.72450953 780624.19839735]

It is not a matrix.


### Qn: 
#### $$e = (A^T \times B) @ C 
+ C^{-1} \times C^T + A^T \times C 
- (A \times C^T - (A^T @ B) \times B^{-1}) 
+ \pi A - \det(C) \times B^T 
+ (A + B^T)(C - A^T) 
- (B^{-1} @ C^T + (A^T \times C) @ B) 
+ (A+C)^{-1} \times B^T - A^T \times B^{-1} 
- ((B @ C^T) \times A^{-1} + 5 \times tr(A) \times C) 
+ \det(A) \times (B^T \times C) 
- 3(B+C)^{-1} \times A^T 
+ \pi^2(A^T+B^T+C^T)(2A-3B+C) 
+ 7(A \times B \times C) 
- \pi^3 B^T \times A^{-1} \times C^T 
+ \det(B)(A+C)^{-1}(A^T-C^T) 
+ 4 \times tr(C) \times (AB-BC) 
+ (A^T+B^T)^{-1}(2C-\pi A) 
- 6\det(A+B) \times C^T 
+ (A @ B @ C)(A+B+C)^{-1} 
+ 9\pi(B^T \times A^T \times C^T) 
- tr(A+B+C) \times B^{-1}(A-C)$$

In [17]:
# @ → matrix multiplication (row × column)
# * → element-wise multiplication (element × element)

import numpy as np
import math

A = np.array([[2,3,1],[4,1,5],[6,2,3]])
B = np.array([[1,4,2],[3,2,6],[5,1,3]])
C = np.array([[3,1,4],[2,5,1],[6,3,2]])

AT = np.einsum('ij->ji',A)
BT = np.einsum('ij->ji',B)
CT = np.einsum('ij->ji',C)

AI = np.linalg.inv(A)
BI = np.linalg.inv(C)
CI = np.linalg.inv(B)

DA = np.linalg.det(A)
DB = np.linalg.det(B)
DC = np.linalg.det(C)


e1 = np.einsum('ij,jk->ik',AT,B) * C

e2 = (np.einsum('ij,jk->ik',BI,CT)) + (np.einsum('ij,jk->ik',AT,C))

e3 = (np.dot(A,CT) - np.dot((AT * B),CI))

e4 = np.pi * A - np.dot(DC,BT)

e5 = (A + BT) @ (C - AT)

e6 = (BI * CT + (AT @ C) * B)

e7 = np.linalg.inv(A+C) @ BT - AT @ BI

e8 = (B * CT) @ AI + 5 * np.einsum('ii',A) * C

e9 = DA * (BT @ C)

e10 = 3 * np.linalg.inv(B+C) @ AT 

e11 = np.pi**2 * (AT + BT + CT) @ (2*A - 3*B + C)

e12 = 7 *(A @ B @ C)

e13 = np.pi**3 * BT @ AI @ CT

e14 = DB * np.linalg.inv(A+C) @ (AT - CT)

e15 = 4 * np.einsum('ii',C) * (A@B - B@C)

e16 = np.linalg.inv(AT + BT) @ (2*C - np.pi * A)

e17 = 6 * np.linalg.det(A+B)*CT

e18 = (A * B * C) @ np.linalg.inv(A+B+C)

e19  = 9*np.pi*(BT @ AT @ CT)

e20 = np.einsum('ii',A+B+C) * BI @ (A - C)

e = e1 + e2 - e3 + e4 + e5 - e6 + e7 - e8 + e9 - e10+ e11 + e12 - e13 + e14 + e15 + e16 - e17 + e18 + e19 - e20

print(e)

[[  682.0090973   2851.46905996 -8616.31711975]
 [ 5911.80110271 -7538.88382517  -636.49406502]
 [ -644.73982086  8250.4630163   4258.62021683]]


In [44]:
# different ways of matrix multiplication

# 1
print(np.dot(A,B))

# 2
print(np.matmul(A,B))

#3 
print(A@B)

#4
print(np.einsum('ij,jk-> ik',A,B))


[[66  0 33]
 [21  9 27]
 [47  8 93]]
[[66  0 33]
 [21  9 27]
 [47  8 93]]
[[66  0 33]
 [21  9 27]
 [47  8 93]]
[[66  0 33]
 [21  9 27]
 [47  8 93]]


In [42]:
#element-wise

# 1
print(A * B)

# 2
np.einsum('ij,ij-> ij',A,B)

[[  6  35 -24]
 [ 18  -5   0]
 [-25 -18  20]]


array([[  6,  35, -24],
       [ 18,  -5,   0],
       [-25, -18,  20]])

### Digitization 
Returns the bin index that each value falls into.

In [56]:
import numpy as np

a = np.array([-0.9,0.4,0.7,1,1.4,1.9,2,2.3,3,3.6,4])

bins = np.array([0,1,2,3])

print(np.digitize(a,bins))

#Indicates whether the interval includes left or right bin edge

print(np.digitize(a,bins,right = True)) #right bin edge is included
print(np.digitize(a,bins,right = False)) #right bin egde is excluded

b = [-75,-0.58,-0.38,1.0,2.8,5.6,6.9,7,7.9]

bins = np.array([0,1,2,3,4,5,6])

print(np.digitize(b,bins))


[0 1 1 2 2 2 3 3 4 4 4]
[0 1 1 1 2 2 2 3 3 4 4]
[0 1 1 2 2 2 3 3 4 4 4]
[0 0 0 2 3 6 7 7 7]


$$ bins = np.array([0,1,2,3]) $$
then,  
(-∞, 0) → bin 0  ← below first edge  
[0,  1) → bin 1  
[1,  2) → bin 2  
[2,  3) → bin 3  
[3,  ∞) → bin 4  

### Count Non-Zero Elements

In [48]:
a = np.array([0,1,2,0,1,3])

non_zero = np.count_nonzero(a)

zero = len(a) - non_zero

print(f'The Array {a} contains {non_zero} non-zero elements and {zero} zero elements.')

The Array [0 1 2 0 1 3] contains 4 non-zero elements and 2 zero elements.


### Sorting

In [49]:
arr = np.array([2,0,5,8,7,6])

asc = np.sort(arr)
print(f'In ascending order: {asc}')

desc = np.sort(arr)[::-1]
print(f'In descending order: {desc}')

In ascending order: [0 2 5 6 7 8]
In descending order: [8 7 6 5 2 0]


### Absolute Value

In [22]:
a = np.array([[-1,2,3,-4,9],[-2,4,3,-7,8]])

absolute = np.abs(a)
print(f'Absolute value of the array: \n{absolute}')

Absolute value of the array: 
[[1 2 3 4 9]
 [2 4 3 7 8]]


### Clipping
Clamps values between a min and max i.e anything below min becomes min, anything above max becomes max.

In [53]:
a1 = np.array([0,1,-4,-3,5,6,7,3,2])
c = a1.clip(0,5)
d = np.clip(a1, 0, 5) # gives the same result

print(f'Clipping the values of \n{a1} \nin the range(0,5): \n{c}')
print(f'Clipping the values of \n{a1} \nin the range(0,5): \n{d}')

Clipping the values of 
[ 0  1 -4 -3  5  6  7  3  2] 
in the range(0,5): 
[0 1 0 0 5 5 5 3 2]
Clipping the values of 
[ 0  1 -4 -3  5  6  7  3  2] 
in the range(0,5): 
[0 1 0 0 5 5 5 3 2]


##### Qn: Result = abs(A)\\(^T\\) * abs(B), then find 1D array of result. Finally digitize and clip it.

In [54]:
A = np.array([[7,6,-5,4,3,2],[7,6,5,4,-3,2]])
B = np.array([[2,6],[7,-9],[-8,10],[11,15],[0,9],[6,7]])

absA = np.abs(A)
absAT = np.einsum('ij->ji',absA)
absB = np.abs(B)
AB = np.einsum('ij,jk->ik',A,B)

result = absAT * absB 
print(result)

result1D = result.flatten()

print()
bins = np.array([0,1,2,3,4,5,6,7])
d = np.digitize(result1D,bins)

print(f'Digitized form of \n{result1D} \nwith bins \n{bins} : \n{d}')

print()
c = result1D.clip(10,50)
print(f'Clipping the values of \n{result1D} \nin the range(0,70): \n{c}')


[[14 42]
 [42 54]
 [40 50]
 [44 60]
 [ 0 27]
 [12 14]]

Digitized form of 
[14 42 42 54 40 50 44 60  0 27 12 14] 
with bins 
[0 1 2 3 4 5 6 7] : 
[8 8 8 8 8 8 8 8 1 8 8 8]

Clipping the values of 
[14 42 42 54 40 50 44 60  0 27 12 14] 
in the range(0,70): 
[14 42 42 50 40 50 44 50 10 27 12 14]
