### Single Dimension NumPy Array

In [2]:
!pip install numpy

In [3]:
!dir

 Volume in drive E is New Volume
 Volume Serial Number is 20A7-3F63

 Directory of E:\Learning_Data_Science\NumPy

07/03/2026  00:10    <DIR>          .
05/03/2026  23:30    <DIR>          ..
27/02/2026  13:45    <DIR>          .ipynb_checkpoints
20/02/2026  14:07    <DIR>          env
07/03/2026  00:10            45,890 NumPy.ipynb
03/03/2026  13:58            13,565 SymPy.ipynb
               2 File(s)         59,455 bytes
               4 Dir(s)  416,326,828,032 bytes free


In [2]:
import numpy as np

arr1 = np.array([5,4,3,6,7,1,2])
print (type(arr1))

print(arr1)


<class 'numpy.ndarray'>
[5 4 3 6 7 1 2]


### Multi-Dimension Array

In [5]:
arr2 = np.array([[1,2,3],[2,3,4],[5,6,7]])

print(arr2)

print(arr2.shape)

[[1 2 3]
 [2 3 4]
 [5 6 7]]
(3, 3)


### Single Dimension Array using arange

In [6]:
arr3 = np.arange(1,10)
arr3

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
arr1 = np.arange(1,10,2)
arr1

array([1, 3, 5, 7, 9])

In [7]:
arr4 = np.arange(1,10).reshape(3,3)
arr4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.full((3,3),9)

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

### Initialize zeros to an array

In [9]:
n1 = np.zeros((2,3))

n1

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
n2 = np.full((11,11),9)
n2

array([[9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

### Initialization of NumPy array while skipping number

In [11]:
n5 = np.arange(1,10,2)
n5

array([1, 3, 5, 7, 9])

In [12]:
import random

n7 = np.random.randint(100,1000,10)
print(n7)

[432 854 115 665 516 934 643 320 430 349]


### Reshaping of array using shape 

In [13]:
n8 = np.array([[1,2,2,3],
             [2,4,3,6],
             [12,18,0,4]])

print(n8)

print(n8.shape)

n8.shape = (2,6)

print(n8)

[[ 1  2  2  3]
 [ 2  4  3  6]
 [12 18  0  4]]
(3, 4)
[[ 1  2  2  3  2  4]
 [ 3  6 12 18  0  4]]


### Transpose

In [14]:
n8.T

array([[ 1,  3],
       [ 2,  6],
       [ 2, 12],
       [ 3, 18],
       [ 2,  0],
       [ 4,  4]])

### 3 ways of Joining/Stacking NumPy Array

In [15]:
a = np.arange(1,11)
b = np.arange(13,23)
c = np.arange(40,50)
d = np.arange(70,80)
e = np.arange(20,30)

print(a,b,c,d,e)

[ 1  2  3  4  5  6  7  8  9 10] [13 14 15 16 17 18 19 20 21 22] [40 41 42 43 44 45 46 47 48 49] [70 71 72 73 74 75 76 77 78 79] [20 21 22 23 24 25 26 27 28 29]


In [16]:
print(np.vstack((a,b,c,d,e))) #stacks the array row-wise(vertically)

[[ 1  2  3  4  5  6  7  8  9 10]
 [13 14 15 16 17 18 19 20 21 22]
 [40 41 42 43 44 45 46 47 48 49]
 [70 71 72 73 74 75 76 77 78 79]
 [20 21 22 23 24 25 26 27 28 29]]


In [19]:
print(np.hstack((a,b,c,d,e))) #stacks the array column-wise (horizontally)

[ 1  2  3  4  5  6  7  8  9 10 13 14 15 16 17 18 19 20 21 22 40 41 42 43
 44 45 46 47 48 49 70 71 72 73 74 75 76 77 78 79 20 21 22 23 24 25 26 27
 28 29]


In [20]:
print(np.column_stack((a,b,c,d,e))) #stacks arrays as columns into a 2D array

[[ 1 13 40 70 20]
 [ 2 14 41 71 21]
 [ 3 15 42 72 22]
 [ 4 16 43 73 23]
 [ 5 17 44 74 24]
 [ 6 18 45 75 25]
 [ 7 19 46 76 26]
 [ 8 20 47 77 27]
 [ 9 21 48 78 28]
 [10 22 49 79 29]]


### NumPy Intersection and Differences

In [21]:
x = np.arange(1,11)
y = np.arange(8,18)

print(x,y)

print(np.intersect1d(x,y))

print(np.setdiff1d(x,y))

print(np.union1d(x,y))

print(np.setxor1d(x,y)) # Symmetric Difference -> Union - Intesection


[ 1  2  3  4  5  6  7  8  9 10] [ 8  9 10 11 12 13 14 15 16 17]
[ 8  9 10]
[1 2 3 4 5 6 7]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
[ 1  2  3  4  5  6  7 11 12 13 14 15 16 17]


### Adding NumPy Array

In [39]:
a = np.array([1,2,3])
b = np.array([13,14,15])

print (np.sum([a,b])) #adds all elements
print ('Axis = 0',np.sum([a,b] ,axis=0)) # axis=0 —> sums down each column
print ('Axis = 1',np.sum([a,b] ,axis=1)) # axis=1 —> sums across each row
print (np.subtract(a,b))


48
Axis = 0 [14 16 18]
Axis = 1 [ 6 42]
[-12 -12 -12]


### Multipying NumPy Array

In [38]:
a = np.array([1,2,3])
b = np.array([13,14,15])

print (np.prod([a,b])) #adds all elements
print ('Axis = 0',np.prod([a,b] ,axis=0)) # axis=0 —> sums down each column
print ('Axis = 1',np.prod([a,b] ,axis=1)) # axis=1 —> sums across each row

16380
Axis = 0 [13 28 45]
Axis = 1 [   6 2730]


In [1]:
# print(help(np))

### NumPy Array Mathematics

In [79]:
p = np.array([10,20,30])

print(p + 1)
print(p // 2)
print(p / 2)
print(p - 2)


[11 21 31]
[ 5 10 15]
[ 5. 10. 15.]
[ 8 18 28]


### Numpy math function

### Numpy basic math function

In [24]:
a1 = np.array([10,20,30,40,50,60,70,80,90,100,1000])

a= [1,2,3,4,5]
b = [2,2,2,2,3]

print(np.mean(a1))
print(np.median(a1))
print(np.std(a1))
print(np.quantile(a1,[0.25,0.75]))
print(np.max(a1))

print(np.cov(a1)) #co-variance
print(np.power(5,3)) #5 power 3
print(np.power(a,b)) 

print(np.square(a)) 
print(np.sqrt(a)) 
print(np.cbrt(a)) 

print(np.remainder(a,b)) # element-wise remainder after division (same as %)



140.9090909090909
60.0
273.04526915561905
[35. 85.]
1000
82009.09090909093
125
[  1   4   9  16 125]
[1 0 1 0 2]
[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[1.         1.25992105 1.44224957 1.58740105 1.70997595]
[1 0 1 0 2]


In [27]:
x = np.array([10,-10,3,-3])
y = np.array([-3,3,-4,4])

# In .mod() & .remainder(), sign of result always matches sign of divisor, if not, add divisor to fix it

print(np.mod(x,y)) 
print(np.remainder(x,y)) # returns element-wise remainder after division (same as .mod())

print(np.fmod(x,y)) # returns the element-wise remainder but the sign follows the dividend (x)

[-2  2 -1  1]
[-2  2 -1  1]
[ 1 -1  3 -3]


In [3]:
x1 = np.array([0.1, 20.4, 19.8, 20, 140, 230, 340, 150, 151.5])

# clamps values between a min and max
# anything below 20 -> 20 and anything above 150 ->150
print(np.clip(x1,20,150)) 

print(np.fix(x1)) # drops the decimal and moves towards zero
print(np.trunc(x1)) #same as fix

#the only difference between them is that fix accepts a second out parameter to store the result
out = np.zeros(len(x1))
np.fix(x1,out)
print('Using out:',out)

[ 20.   20.4  20.   20.  140.  150.  150.  150.  150. ]
[  0.  20.  19.  20. 140. 230. 340. 150. 151.]
[  0.  20.  19.  20. 140. 230. 340. 150. 151.]
Using out: [  0.  20.  19.  20. 140. 230. 340. 150. 151.]


In [43]:
s=np.array([1,2,3,4])

print(np.cumsum(s)) # each element is the sum of all previous elements plus itself

print(np.reciprocal(s)) #if the element are integer then integer division takes places

s1 = np.array([1,2,3,4,5],dtype = float) #if elements are float then, it returns 1/x 
print(np.reciprocal(s1))

[ 1  3  6 10]
[1 0 0 0]
[1.         0.5        0.33333333 0.25       0.2       ]


In [143]:
a= np.array([1.23445,14.090909,1.33333333])
np.round(a,decimals = 2)

array([ 1.23, 14.09,  1.33])

In [44]:
t=np.array([20,18,28,4])
s=np.array([1,2,3,4])

print(np.gcd(t,s))
print(np.lcm(t,s))

[1 2 1 4]
[20 18 84  4]


### Trigonometric Functions

In [47]:
import warnings
warnings.filterwarnings('ignore')

a= [0.5,1.0,1.5,2.5]

print(np.sin(a))
print(np.cos(a))
print(np.tan(a))
print()
#Inverse
print(np.arcsin(a))
print(np.arccos(a))
print(np.arctan(a))
print()
#Inverse Hyperbolic
print(np.arcsinh(a))
print(np.arccosh(a))
print(np.arctanh(a))
print()
# Hyperbolic
print(np.sinh(a))
print(np.cosh(a))
print(np.tanh(a))

print()
print(np.exp2(a)) # 2^x
print(np.expm1(a)) #e^x - 1
print(np.log1p(a))
print(np.log10(a))

b = np.log1p(a) # log(1+x) natural log

print(np.expm1(b))



[0.47942554 0.84147098 0.99749499 0.59847214]
[ 0.87758256  0.54030231  0.0707372  -0.80114362]
[ 0.54630249  1.55740772 14.10141995 -0.7470223 ]

[0.52359878 1.57079633        nan        nan]
[1.04719755 0.                nan        nan]
[0.46364761 0.78539816 0.98279372 1.19028995]

[0.48121183 0.88137359 1.19476322 1.64723115]
[       nan 0.         0.96242365 1.56679924]
[0.54930614        inf        nan        nan]

[0.52109531 1.17520119 2.12927946 6.05020448]
[1.12762597 1.54308063 2.35240962 6.13228948]
[0.46211716 0.76159416 0.90514825 0.9866143 ]

[1.41421356 2.         2.82842712 5.65685425]
[ 0.64872127  1.71828183  3.48168907 11.18249396]
[0.40546511 0.69314718 0.91629073 1.25276297]
[-0.30103     0.          0.17609126  0.39794001]
[0.5 1.  1.5 2.5]


### Conversion from degree to radian and vice-versa

##### radians = degrees × ($\pi$/180)  
##### degrees = radians × (180/$\pi$)


In [50]:
x = np.array([1,123,45,67,0.2])

print(np.deg2rad(x)) # converts degrees → radians
print(np.rad2deg(x)) # converts radians → degrees

[0.01745329 2.14675498 0.78539816 1.1693706  0.00349066]
[  57.29577951 7047.38088011 2578.31007809 3838.81722738   11.4591559 ]


In [51]:
a1 = [0.5,1.0,1.5,2.5]

print(np.ceil(a1)) # returns the smallest integer greater than the number
print(np.floor(a1)) # returns the largest integer samller than the number

[1. 1. 2. 3.]
[0. 1. 1. 2.]


### Saving and Loading NumPy Array

In [52]:
n1 = np.array([1,4,7,0])

np.save('Array1',n1)

print(np.load('Array1.npy'))

[1 4 7 0]


#### Qn: Create a NumPy array with data ranging from 10 to 1000, calculate the covariance using both np.cov() and from scratch, then compare the results.

In [64]:
x = np.random.randint(10,1000,20)
y = np.random.randint(10,1000,20)

print(f'x = {x}') 
print(f'y = {y}') 

x = [219 747 483 663 190 792 342 105 359 649 230  65 474 250 187 501 900 103
  83 700]
y = [ 50 855 101 658 166 793 565 697 888 744 266 209 511 646 707 334  75 471
 338 480]


##### Manually from scratch

In [78]:
x_total = 0
y_total = 0

n = len(x)
for i in range(n):
    x_total += x[i]
    y_total += y[i]

x_mean = x_total/len(x)
y_mean = y_total/len(y)

total = 0

for j in range(n):
    total += ((x[j] - x_mean) * (y[j] - y_mean))

m_cov = total / n

print(f'The covariance of x and y (calculated manually): {m_cov}')
    

The covariance of x and y (calculated manually): 13937.830000000007


##### Using NumPy (np.cov())

In [73]:
# np.cov() gives covariance matrix from which we extract cov(x,y) using [0,1]
# [[cov(x,x),  cov(x,y)],     
#  [cov(y,x),  cov(y,y)]]

np_cov = np.cov(x,y)[0,1]

print(f'The covariance of x and y (calculated using NumPy): {np_cov}')

The covariance of x and y (calculated using NumPy): 14671.400000000001


##### Difference between the two and the reason why?

In [74]:
print(f'The difference between the covariances calculated manually and using NumPy: {abs(m_cov - np_cov)} ')

The difference between the covariances calculated manually and using NumPy: 13986.229999999998 


##### The reason why the two values are different is that np.cov() calculates sample covariance i.e. using n-1 but manually, we calculated population covariance i.e using N.

In [79]:
# Population Covariance can also be calculated using NumPy

pop_cov = np.cov(x,y,ddof = 0)[0,1]

print(f'The population covariance of x and y calculated using NumPy : {pop_cov}')

The population covariance of x and y calculated using NumPy : 13937.830000000002


In [80]:
print(f'The diff between the covariances calculated manually and NumPy(population):{abs(m_cov-pop_cov)}')

The difference between the covariances calculated manually and using NumPy: 5.4569682106375694e-12 
