### Singular Value Decomposition

### Calculated Manually

In [47]:
import numpy as np

A = np.array([[3,1],[1,3]])

AT = A.T

X = AT @ A

print(f'A\u1D40 :\n{AT}')
print(f'A\u1D40.A :\n{X}')

evalue, evector = np.linalg.eig(X)

i = np.argsort(evalue)[::-1]  #sorting in descending order
evalue = evalue[i]
evector = evector[:,i]

print('Eigen Values of A\u1D40.A:',evalue)

print('Eigen Vector of A\u1D40.A:',evector,sep='\n')

singular_value = np.sqrt(evalue)

S = np.diag(singular_value)

print(f'Singular Vector (S) :\n{S}')

V = evector
VT = V.T

print(f'Right Singular Vector (V\u1D40) :\n{VT}')

m,n = A.shape
r = np.linalg.matrix_rank(A)

U = np.zeros((m,r),dtype = float)

for i in range(r):
    vi = evector[:,i]

    U[:,i] = (1/singular_value[i]) * (A @ vi)
 
print(f'Left Singular Vector (U) :\n{U}')

print(f'Reconstruction of A: \n{U @ S @ VT}')


Aᵀ :
[[3 1]
 [1 3]]
Aᵀ.A :
[[10  6]
 [ 6 10]]
Eigen Values of Aᵀ.A: [16.  4.]
Eigen Vector of Aᵀ.A:
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
Singular Vector (S) :
[[4. 0.]
 [0. 2.]]
Right Singular Vector (Vᵀ) :
[[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]
Left Singular Vector (U) :
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
Reconstruction of A: 
[[3. 1.]
 [1. 3.]]


### Calculated Using NumPy

In [55]:
A = np.array([[3,1],[1,3]])

U,S_Values,V = np.linalg.svd(A)

S = np.diag(S_Values)

print(f'Left Singular Vector (U) :\n{U}')
print(f'Singular Vector (S) :\n{S}')
print(f'Right Singular Vector (V\u1D40) :\n{V}')

print(f'Reconstruction of A: \n{U @ S @ V}')


Left Singular Vector (U) :
[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]
Singular Vector (S) :
[[4. 0.]
 [0. 2.]]
Right Singular Vector (Vᵀ) :
[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]
Reconstruction of A: 
[[3. 1.]
 [1. 3.]]
